import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

/**
 * Generates a professional, printer-friendly Meeting Report PDF document.
 * Uses jspdf + jspdf-autotable for client-side vector text generation,
 * multi-page text wrapping, auto-pagination, and brand colors.
 *
 * @param {object} data - { job, transcript, summary }
 */
export function generateMeetingPdf(data) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const { job = {}, transcript = {}, summary = {} } = data
  const {
    executive_summary = '',
    key_decisions = [],
    action_items = [],
    open_questions = [],
  } = summary
  const { segments = [], num_speakers = 0 } = transcript || {}

  // Brand Palette RGBs
  const COLOR_TEXT = [36, 52, 71]       // #243447 Deep blue-gray
  const COLOR_TEAL = [94, 190, 196]     // #5EBEC4 Soft teal
  const COLOR_PINK = [249, 44, 133]     // #F92C85 Bright pink
  const COLOR_YELLOW = [245, 200, 75]   // #F5C84B Warm yellow
  const COLOR_MUTED = [90, 110, 133]    // #5A6E85 Gray

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const marginX = 15
  let currentY = 15

  // Helper for adding new page with header/footer
  const checkPageBreak = (neededHeight = 15) => {
    if (currentY + neededHeight > pageHeight - 20) {
      doc.addPage()
      currentY = 20
      return true
    }
    return false
  }

  // ── HEADER BANNER ────────────────────────────────────────────────────────
  doc.setFillColor(...COLOR_TEAL)
  doc.rect(0, 0, pageWidth, 8, 'F')
  doc.setFillColor(...COLOR_PINK)
  doc.rect(0, 8, pageWidth, 2, 'F')

  currentY = 20

  // ── TITLE PAGE / METADATA ────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...COLOR_TEXT)
  doc.text('MEETING SUMMARY REPORT', marginX, currentY)
  currentY += 8

  // Meeting Title
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLOR_PINK)
  const titleText = job.original_filename || 'Meeting Recording'
  doc.text(titleText, marginX, currentY)
  currentY += 10

  // Metadata Box
  doc.setFillColor(253, 245, 223) // #FDF5DF Warm cream
  doc.setDrawColor(...COLOR_TEXT)
  doc.setLineWidth(0.5)
  doc.roundedRect(marginX, currentY, pageWidth - 2 * marginX, 22, 3, 3, 'FD')

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...COLOR_TEXT)

  const formattedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  const durationText = job.duration_seconds
    ? `${Math.floor(job.duration_seconds / 60)}m ${Math.round(job.duration_seconds % 60)}s`
    : 'Not specified'

  doc.text(`Date: ${formattedDate}`, marginX + 5, currentY + 7)
  doc.text(`Duration: ${durationText}`, marginX + 65, currentY + 7)
  doc.text(`Participants: ${num_speakers > 0 ? `${num_speakers} Speakers` : 'N/A'}`, marginX + 120, currentY + 7)

  doc.text(`Generated by: Meeting Summarizer`, marginX + 5, currentY + 15)
  doc.text(`Privacy Status: 100% Local Verified Process`, marginX + 65, currentY + 15)

  currentY += 30

  // Helper for Section Headings
  const renderSectionHeader = (title, color = COLOR_TEAL) => {
    checkPageBreak(20)
    doc.setFillColor(...color)
    doc.rect(marginX, currentY, 3.5, 7, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(...COLOR_TEXT)
    doc.text(title, marginX + 6, currentY + 5.5)
    currentY += 10
  }

  // ── EXECUTIVE SUMMARY ────────────────────────────────────────────────────
  if (executive_summary) {
    renderSectionHeader('EXECUTIVE SUMMARY', COLOR_TEAL)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(...COLOR_TEXT)

    const summaryLines = doc.splitTextToSize(executive_summary, pageWidth - 2 * marginX)
    summaryLines.forEach((line) => {
      checkPageBreak(6)
      doc.text(line, marginX, currentY)
      currentY += 5
    })
    currentY += 6
  }

  // ── KEY DECISIONS ────────────────────────────────────────────────────────
  if (key_decisions.length > 0) {
    renderSectionHeader('KEY DECISIONS & RATIONALES', COLOR_YELLOW)

    key_decisions.forEach((d, idx) => {
      checkPageBreak(15)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(10)
      doc.setTextColor(...COLOR_TEXT)
      doc.text(`[Decision ${idx + 1}] ${d.decision}`, marginX + 2, currentY)
      currentY += 5

      if (d.rationale) {
        doc.setFont('helvetica', 'italic')
        doc.setFontSize(9)
        doc.setTextColor(...COLOR_MUTED)
        const ratLines = doc.splitTextToSize(`Rationale: ${d.rationale}`, pageWidth - 2 * marginX - 6)
        ratLines.forEach((rLine) => {
          checkPageBreak(5)
          doc.text(rLine, marginX + 6, currentY)
          currentY += 4.5
        })
      }
      currentY += 3
    })
    currentY += 4
  }

  // ── ACTION ITEMS TABLE ──────────────────────────────────────────────────
  if (action_items.length > 0) {
    renderSectionHeader('ACTION ITEMS MATRIX', COLOR_PINK)

    const tableRows = action_items.map((item) => [
      item.owner || 'Not specified',
      item.task || 'Not specified',
      item.deadline || 'Not specified',
      (item.priority || 'medium').toUpperCase(),
    ])

    autoTable(doc, {
      startY: currentY,
      margin: { left: marginX, right: marginX },
      head: [['Owner', 'Action Item', 'Deadline', 'Priority']],
      body: tableRows,
      theme: 'grid',
      headStyles: {
        fillColor: COLOR_TEAL,
        textColor: COLOR_TEXT,
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: {
        textColor: COLOR_TEXT,
        fontSize: 9,
      },
      columnStyles: {
        0: { cellWidth: 35, fontStyle: 'bold' },
        1: { cellWidth: 85 },
        2: { cellWidth: 30 },
        3: { cellWidth: 30, fontStyle: 'bold' },
      },
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 3) {
          const val = data.cell.raw
          if (val === 'HIGH') {
            data.cell.styles.textColor = COLOR_PINK
          } else if (val === 'LOW') {
            data.cell.styles.textColor = COLOR_MUTED
          }
        }
      },
    })

    currentY = doc.lastAutoTable.finalY + 10
  }

  // ── OPEN QUESTIONS ───────────────────────────────────────────────────────
  renderSectionHeader('OPEN QUESTIONS & UNRESOLVED ITEMS', COLOR_TEAL)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9.5)
  doc.setTextColor(...COLOR_TEXT)

  if (open_questions.length === 0) {
    doc.text('No unresolved questions were identified.', marginX, currentY)
    currentY += 8
  } else {
    open_questions.forEach((q, idx) => {
      checkPageBreak(7)
      const qLines = doc.splitTextToSize(`? ${idx + 1}. ${q}`, pageWidth - 2 * marginX)
      qLines.forEach((qLine) => {
        checkPageBreak(5)
        doc.text(qLine, marginX, currentY)
        currentY += 5
      })
    })
    currentY += 6
  }

  // ── FULL TRANSCRIPT ──────────────────────────────────────────────────────
  if (segments.length > 0) {
    renderSectionHeader('FULL SPEAKER-DIARIZED TRANSCRIPT', COLOR_PINK)

    segments.forEach((seg) => {
      checkPageBreak(12)

      const minutes = Math.floor(seg.start_time / 60)
      const seconds = Math.floor(seg.start_time % 60)
      const timeStamp = `[${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}]`
      const speakerName = seg.speaker || 'Unknown Speaker'

      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9)
      doc.setTextColor(...COLOR_TEXT)
      doc.text(`${timeStamp} ${speakerName}`, marginX, currentY)
      currentY += 4.5

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(40, 55, 75)

      const textLines = doc.splitTextToSize(seg.text, pageWidth - 2 * marginX - 4)
      textLines.forEach((tLine) => {
        checkPageBreak(4.5)
        doc.text(tLine, marginX + 4, currentY)
        currentY += 4.5
      })
      currentY += 2
    })
    currentY += 8
  }

  // ── FINAL NOTES & FOOTER PAGINATION ──────────────────────────────────────
  const totalPages = doc.internal.getNumberOfPages()

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setDrawColor(220, 220, 220)
    doc.setLineWidth(0.3)
    doc.line(marginX, pageHeight - 12, pageWidth - marginX, pageHeight - 12)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...COLOR_MUTED)
    doc.text(`Meeting Summarizer • Page ${i} of ${totalPages}`, marginX, pageHeight - 7)
    doc.text(`Turn conversations into clarity.`, pageWidth - marginX, pageHeight - 7, { align: 'right' })
  }

  // Save the PDF file
  const filename = (job.original_filename || 'meeting_summary')
    .replace(/\.[^/.]+$/, '')
    .replace(/[^a-z0-9]/gi, '_')
  doc.save(`${filename}_Meeting_Report.pdf`)
}
